WEB_DIRECTORY = "./js"

# Import from all organized node modules
from .image_nodes import NODE_CLASS_MAPPINGS as IMAGE_MAPPINGS
from .image_nodes import NODE_DISPLAY_NAME_MAPPINGS as IMAGE_DISPLAY_MAPPINGS
from .latent_nodes import NODE_CLASS_MAPPINGS as LATENT_MAPPINGS
from .latent_nodes import NODE_DISPLAY_NAME_MAPPINGS as LATENT_DISPLAY_MAPPINGS
from .multi_value_nodes import NODE_CLASS_MAPPINGS as MULTI_VALUE_MAPPINGS
from .multi_value_nodes import \
    NODE_DISPLAY_NAME_MAPPINGS as MULTI_VALUE_DISPLAY_MAPPINGS
from .slider_nodes import NODE_CLASS_MAPPINGS as SLIDER_MAPPINGS
from .slider_nodes import NODE_DISPLAY_NAME_MAPPINGS as SLIDER_DISPLAY_MAPPINGS
from .switch_nodes import NODE_CLASS_MAPPINGS as SWITCH_MAPPINGS
from .switch_nodes import NODE_DISPLAY_NAME_MAPPINGS as SWITCH_DISPLAY_MAPPINGS

# Merge all node class mappings
NODE_CLASS_MAPPINGS = {}
NODE_CLASS_MAPPINGS.update(SLIDER_MAPPINGS)
NODE_CLASS_MAPPINGS.update(MULTI_VALUE_MAPPINGS)
NODE_CLASS_MAPPINGS.update(SWITCH_MAPPINGS)
NODE_CLASS_MAPPINGS.update(IMAGE_MAPPINGS)
NODE_CLASS_MAPPINGS.update(LATENT_MAPPINGS)

# Merge all display name mappings
NODE_DISPLAY_NAME_MAPPINGS = {}
NODE_DISPLAY_NAME_MAPPINGS.update(SLIDER_DISPLAY_MAPPINGS)
NODE_DISPLAY_NAME_MAPPINGS.update(MULTI_VALUE_DISPLAY_MAPPINGS)
NODE_DISPLAY_NAME_MAPPINGS.update(SWITCH_DISPLAY_MAPPINGS)
NODE_DISPLAY_NAME_MAPPINGS.update(IMAGE_DISPLAY_MAPPINGS)
NODE_DISPLAY_NAME_MAPPINGS.update(LATENT_DISPLAY_MAPPINGS)

__all__ = ['NODE_CLASS_MAPPINGS', 'NODE_DISPLAY_NAME_MAPPINGS', 'WEB_DIRECTORY']
